// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mjazhbxbgqbaefeqtkdt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1qYXpoYnhiZ3FiYWVmZXF0a2R0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDExOTg2NTYsImV4cCI6MjA1Njc3NDY1Nn0.7u3X626zwjbakf2bNBIjXsUqjp2mE7kv8k1XeEu6P9A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);